# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Nov 12 14:29:30 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(767, 734)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 0, 641, 301))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(210, 20, 161, 281))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.listArestas = QtGui.QListView(self.groupBox_2)
        self.listArestas.setGeometry(QtCore.QRect(0, 30, 161, 171))
        self.listArestas.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listArestas.setObjectName(_fromUtf8("listArestas"))
        self.layoutWidget = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 210, 161, 66))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineNomeAresta = QtGui.QLineEdit(self.layoutWidget)
        self.lineNomeAresta.setObjectName(_fromUtf8("lineNomeAresta"))
        self.horizontalLayout.addWidget(self.lineNomeAresta)
        self.pushAddAresta = QtGui.QPushButton(self.layoutWidget)
        self.pushAddAresta.setObjectName(_fromUtf8("pushAddAresta"))
        self.horizontalLayout.addWidget(self.pushAddAresta)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.pushRemoverAresta = QtGui.QPushButton(self.layoutWidget)
        self.pushRemoverAresta.setObjectName(_fromUtf8("pushRemoverAresta"))
        self.verticalLayout_4.addWidget(self.pushRemoverAresta)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 20, 181, 281))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.listVertices = QtGui.QListView(self.groupBox_3)
        self.listVertices.setGeometry(QtCore.QRect(20, 30, 161, 171))
        self.listVertices.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listVertices.setObjectName(_fromUtf8("listVertices"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 210, 161, 66))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineNomeVertice = QtGui.QLineEdit(self.layoutWidget1)
        self.lineNomeVertice.setObjectName(_fromUtf8("lineNomeVertice"))
        self.horizontalLayout_2.addWidget(self.lineNomeVertice)
        self.pushAddVertice = QtGui.QPushButton(self.layoutWidget1)
        self.pushAddVertice.setObjectName(_fromUtf8("pushAddVertice"))
        self.horizontalLayout_2.addWidget(self.pushAddVertice)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.pushRemoverVertice = QtGui.QPushButton(self.layoutWidget1)
        self.pushRemoverVertice.setObjectName(_fromUtf8("pushRemoverVertice"))
        self.verticalLayout_3.addWidget(self.pushRemoverVertice)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(390, 20, 251, 291))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.listConexoes = QtGui.QListView(self.groupBox_4)
        self.listConexoes.setGeometry(QtCore.QRect(0, 30, 241, 171))
        self.listConexoes.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listConexoes.setObjectName(_fromUtf8("listConexoes"))
        self.layoutWidget2 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 240, 241, 31))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.linePesoNo = QtGui.QLineEdit(self.layoutWidget2)
        self.linePesoNo.setObjectName(_fromUtf8("linePesoNo"))
        self.horizontalLayout_4.addWidget(self.linePesoNo)
        self.pushAddConexao = QtGui.QPushButton(self.layoutWidget2)
        self.pushAddConexao.setObjectName(_fromUtf8("pushAddConexao"))
        self.horizontalLayout_4.addWidget(self.pushAddConexao)
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget3.setGeometry(QtCore.QRect(0, 210, 248, 31))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboVertice1 = QtGui.QComboBox(self.layoutWidget3)
        self.comboVertice1.setObjectName(_fromUtf8("comboVertice1"))
        self.horizontalLayout_3.addWidget(self.comboVertice1)
        self.comboAresta = QtGui.QComboBox(self.layoutWidget3)
        self.comboAresta.setObjectName(_fromUtf8("comboAresta"))
        self.horizontalLayout_3.addWidget(self.comboAresta)
        self.comboVertice2 = QtGui.QComboBox(self.layoutWidget3)
        self.comboVertice2.setObjectName(_fromUtf8("comboVertice2"))
        self.horizontalLayout_3.addWidget(self.comboVertice2)
        self.pushGerar = QtGui.QPushButton(self.centralWidget)
        self.pushGerar.setGeometry(QtCore.QRect(580, 640, 87, 27))
        self.pushGerar.setObjectName(_fromUtf8("pushGerar"))
        self.layoutWidget4 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(60, 320, 601, 311))
        self.layoutWidget4.setObjectName(_fromUtf8("layoutWidget4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget4)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.checkDirecionado = QtGui.QCheckBox(self.groupBox_5)
        self.checkDirecionado.setGeometry(QtCore.QRect(10, 30, 161, 21))
        self.checkDirecionado.setObjectName(_fromUtf8("checkDirecionado"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(190, 0, 371, 309))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.checkExisteLaco = QtGui.QCheckBox(self.groupBox_6)
        self.checkExisteLaco.setGeometry(QtCore.QRect(10, 30, 181, 22))
        self.checkExisteLaco.setObjectName(_fromUtf8("checkExisteLaco"))
        self.checkExisteParalela = QtGui.QCheckBox(self.groupBox_6)
        self.checkExisteParalela.setGeometry(QtCore.QRect(10, 60, 241, 22))
        self.checkExisteParalela.setObjectName(_fromUtf8("checkExisteParalela"))
        self.checkExisteIsolado = QtGui.QCheckBox(self.groupBox_6)
        self.checkExisteIsolado.setGeometry(QtCore.QRect(10, 90, 241, 22))
        self.checkExisteIsolado.setObjectName(_fromUtf8("checkExisteIsolado"))
        self.checkOrdem = QtGui.QCheckBox(self.groupBox_6)
        self.checkOrdem.setGeometry(QtCore.QRect(10, 120, 241, 22))
        self.checkOrdem.setObjectName(_fromUtf8("checkOrdem"))
        self.checkExisteCiclo = QtGui.QCheckBox(self.groupBox_6)
        self.checkExisteCiclo.setGeometry(QtCore.QRect(10, 150, 241, 22))
        self.checkExisteCiclo.setObjectName(_fromUtf8("checkExisteCiclo"))
        self.checkConexo = QtGui.QCheckBox(self.groupBox_6)
        self.checkConexo.setGeometry(QtCore.QRect(10, 180, 241, 22))
        self.checkConexo.setObjectName(_fromUtf8("checkConexo"))
        self.checkCaminhoCurto = QtGui.QCheckBox(self.groupBox_6)
        self.checkCaminhoCurto.setGeometry(QtCore.QRect(10, 210, 171, 22))
        self.checkCaminhoCurto.setObjectName(_fromUtf8("checkCaminhoCurto"))
        self.checkGrau = QtGui.QCheckBox(self.groupBox_6)
        self.checkGrau.setGeometry(QtCore.QRect(10, 240, 241, 22))
        self.checkGrau.setObjectName(_fromUtf8("checkGrau"))
        self.checkAdjacencia = QtGui.QCheckBox(self.groupBox_6)
        self.checkAdjacencia.setGeometry(QtCore.QRect(10, 270, 241, 22))
        self.checkAdjacencia.setObjectName(_fromUtf8("checkAdjacencia"))
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_6)
        self.layoutWidget5.setGeometry(QtCore.QRect(180, 210, 174, 27))
        self.layoutWidget5.setObjectName(_fromUtf8("layoutWidget5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboCaminhoInicio = QtGui.QComboBox(self.layoutWidget5)
        self.comboCaminhoInicio.setObjectName(_fromUtf8("comboCaminhoInicio"))
        self.horizontalLayout_6.addWidget(self.comboCaminhoInicio)
        self.comboCaminhoFim = QtGui.QComboBox(self.layoutWidget5)
        self.comboCaminhoFim.setObjectName(_fromUtf8("comboCaminhoFim"))
        self.horizontalLayout_6.addWidget(self.comboCaminhoFim)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        self.layoutWidget6 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget6.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget6.setObjectName(_fromUtf8("layoutWidget6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.layoutWidget7 = QtGui.QWidget(self.centralWidget)
        self.layoutWidget7.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget7.setObjectName(_fromUtf8("layoutWidget7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 767, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuArquivo = QtGui.QMenu(self.menuBar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        self.menuAjuda = QtGui.QMenu(self.menuBar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.actionVai_se_fuder = QtGui.QAction(MainWindow)
        self.actionVai_se_fuder.setObjectName(_fromUtf8("actionVai_se_fuder"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.actionNovo = QtGui.QAction(MainWindow)
        self.actionNovo.setObjectName(_fromUtf8("actionNovo"))
        self.menuArquivo.addAction(self.actionNovo)
        self.menuArquivo.addAction(self.actionSair)
        self.menuAjuda.addAction(self.actionSobre)
        self.menuBar.addAction(self.menuArquivo.menuAction())
        self.menuBar.addAction(self.menuAjuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listVertices, self.lineNomeVertice)
        MainWindow.setTabOrder(self.lineNomeVertice, self.pushAddVertice)
        MainWindow.setTabOrder(self.pushAddVertice, self.pushRemoverVertice)
        MainWindow.setTabOrder(self.pushRemoverVertice, self.listArestas)
        MainWindow.setTabOrder(self.listArestas, self.lineNomeAresta)
        MainWindow.setTabOrder(self.lineNomeAresta, self.pushAddAresta)
        MainWindow.setTabOrder(self.pushAddAresta, self.pushRemoverAresta)
        MainWindow.setTabOrder(self.pushRemoverAresta, self.listConexoes)
        MainWindow.setTabOrder(self.listConexoes, self.comboVertice1)
        MainWindow.setTabOrder(self.comboVertice1, self.comboAresta)
        MainWindow.setTabOrder(self.comboAresta, self.comboVertice2)
        MainWindow.setTabOrder(self.comboVertice2, self.linePesoNo)
        MainWindow.setTabOrder(self.linePesoNo, self.pushAddConexao)
        MainWindow.setTabOrder(self.pushAddConexao, self.checkDirecionado)
        MainWindow.setTabOrder(self.checkDirecionado, self.checkExisteLaco)
        MainWindow.setTabOrder(self.checkExisteLaco, self.checkExisteParalela)
        MainWindow.setTabOrder(self.checkExisteParalela, self.checkExisteIsolado)
        MainWindow.setTabOrder(self.checkExisteIsolado, self.checkOrdem)
        MainWindow.setTabOrder(self.checkOrdem, self.checkExisteCiclo)
        MainWindow.setTabOrder(self.checkExisteCiclo, self.checkConexo)
        MainWindow.setTabOrder(self.checkConexo, self.checkCaminhoCurto)
        MainWindow.setTabOrder(self.checkCaminhoCurto, self.comboCaminhoInicio)
        MainWindow.setTabOrder(self.comboCaminhoInicio, self.comboCaminhoFim)
        MainWindow.setTabOrder(self.comboCaminhoFim, self.checkGrau)
        MainWindow.setTabOrder(self.checkGrau, self.checkAdjacencia)
        MainWindow.setTabOrder(self.checkAdjacencia, self.pushGerar)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Grafo", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Arestas", None))
        self.pushAddAresta.setText(_translate("MainWindow", "Adicionar", None))
        self.pushRemoverAresta.setText(_translate("MainWindow", "Remover", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Vértices", None))
        self.pushAddVertice.setText(_translate("MainWindow", "Adicionar", None))
        self.pushRemoverVertice.setText(_translate("MainWindow", "Remover", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Conexões", None))
        self.label.setText(_translate("MainWindow", "Peso:", None))
        self.pushAddConexao.setText(_translate("MainWindow", "Adicionar", None))
        self.pushGerar.setText(_translate("MainWindow", "Gerar", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Opções do grafo", None))
        self.checkDirecionado.setText(_translate("MainWindow", "Grafo direcionado", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Identificar", None))
        self.checkExisteLaco.setText(_translate("MainWindow", "Existência de laços", None))
        self.checkExisteParalela.setText(_translate("MainWindow", "Existência de arestas paralelas", None))
        self.checkExisteIsolado.setText(_translate("MainWindow", "Existência de nó isolado", None))
        self.checkOrdem.setText(_translate("MainWindow", "Ordem do grafo", None))
        self.checkExisteCiclo.setText(_translate("MainWindow", "Existência de ciclos", None))
        self.checkConexo.setText(_translate("MainWindow", "Se é conexo", None))
        self.checkCaminhoCurto.setText(_translate("MainWindow", "Caminho mais curto", None))
        self.checkGrau.setText(_translate("MainWindow", "Grau de cada nó", None))
        self.checkAdjacencia.setText(_translate("MainWindow", "Adjacência dos nós", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "Ar&quivo", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "A&juda", None))
        self.actionSair.setText(_translate("MainWindow", "&Sair", None))
        self.actionVai_se_fuder.setText(_translate("MainWindow", "&Vai se fuder", None))
        self.actionSobre.setText(_translate("MainWindow", "&Sobre", None))
        self.actionNovo.setText(_translate("MainWindow", "&Novo", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

