from grafo import Grafo

grafo = Grafo()
grafo.addAresta('a')
grafo.addAresta('b')
grafo.addAresta('c')
grafo.addAresta('d')
grafo.addAresta('e')
grafo.addAresta('f')
grafo.addVertice('1')
grafo.addVertice('2')
grafo.addVertice('3')
grafo.addVertice('4')
grafo.addVertice('5')
grafo.addConexao('1', 'a', '2', 1)
grafo.addConexao('1', 'f', '2', 1)
grafo.addConexao('2', 'b', '4', 1)
grafo.addConexao('3', 'c', '4', 1)
grafo.addConexao('1', 'd', '4', 1)
grafo.addConexao('1', 'e', '3', 1)

print(grafo.getTodosGraus())
