# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/mainwindow.ui'
#
# Created: Sun Nov 16 19:33:05 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(614, 640)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.listVertices = QtGui.QListView(self.groupBox_3)
        self.listVertices.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listVertices.setObjectName(_fromUtf8("listVertices"))
        self.gridLayout_3.addWidget(self.listVertices, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineNomeVertice = QtGui.QLineEdit(self.groupBox_3)
        self.lineNomeVertice.setObjectName(_fromUtf8("lineNomeVertice"))
        self.horizontalLayout_2.addWidget(self.lineNomeVertice)
        self.pushAddVertice = QtGui.QPushButton(self.groupBox_3)
        self.pushAddVertice.setObjectName(_fromUtf8("pushAddVertice"))
        self.horizontalLayout_2.addWidget(self.pushAddVertice)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.pushRemoverVertice = QtGui.QPushButton(self.groupBox_3)
        self.pushRemoverVertice.setObjectName(_fromUtf8("pushRemoverVertice"))
        self.verticalLayout_3.addWidget(self.pushRemoverVertice)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineNomeAresta = QtGui.QLineEdit(self.groupBox_2)
        self.lineNomeAresta.setObjectName(_fromUtf8("lineNomeAresta"))
        self.horizontalLayout.addWidget(self.lineNomeAresta)
        self.pushAddAresta = QtGui.QPushButton(self.groupBox_2)
        self.pushAddAresta.setObjectName(_fromUtf8("pushAddAresta"))
        self.horizontalLayout.addWidget(self.pushAddAresta)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.pushRemoverAresta = QtGui.QPushButton(self.groupBox_2)
        self.pushRemoverAresta.setObjectName(_fromUtf8("pushRemoverAresta"))
        self.verticalLayout_4.addWidget(self.pushRemoverAresta)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 1, 0, 1, 1)
        self.listArestas = QtGui.QListView(self.groupBox_2)
        self.listArestas.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listArestas.setObjectName(_fromUtf8("listArestas"))
        self.gridLayout_4.addWidget(self.listArestas, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.listConexoes = QtGui.QListView(self.groupBox_4)
        self.listConexoes.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.listConexoes.setObjectName(_fromUtf8("listConexoes"))
        self.gridLayout_5.addWidget(self.listConexoes, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.comboVertice1 = QtGui.QComboBox(self.groupBox_4)
        self.comboVertice1.setObjectName(_fromUtf8("comboVertice1"))
        self.horizontalLayout_3.addWidget(self.comboVertice1)
        self.comboAresta = QtGui.QComboBox(self.groupBox_4)
        self.comboAresta.setObjectName(_fromUtf8("comboAresta"))
        self.horizontalLayout_3.addWidget(self.comboAresta)
        self.comboVertice2 = QtGui.QComboBox(self.groupBox_4)
        self.comboVertice2.setObjectName(_fromUtf8("comboVertice2"))
        self.horizontalLayout_3.addWidget(self.comboVertice2)
        self.gridLayout_5.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_4.addWidget(self.label)
        self.linePesoNo = QtGui.QLineEdit(self.groupBox_4)
        self.linePesoNo.setObjectName(_fromUtf8("linePesoNo"))
        self.horizontalLayout_4.addWidget(self.linePesoNo)
        self.pushAddConexao = QtGui.QPushButton(self.groupBox_4)
        self.pushAddConexao.setObjectName(_fromUtf8("pushAddConexao"))
        self.horizontalLayout_4.addWidget(self.pushAddConexao)
        self.gridLayout_5.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.pushRemoveConexao = QtGui.QPushButton(self.groupBox_4)
        self.pushRemoveConexao.setObjectName(_fromUtf8("pushRemoveConexao"))
        self.gridLayout_5.addWidget(self.pushRemoveConexao, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_7.setMouseTracking(False)
        self.groupBox_7.setFlat(False)
        self.groupBox_7.setCheckable(False)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.checkDirecionado = QtGui.QCheckBox(self.groupBox_7)
        self.checkDirecionado.setGeometry(QtCore.QRect(0, 20, 136, 21))
        self.checkDirecionado.setObjectName(_fromUtf8("checkDirecionado"))
        self.gridLayout_6.addWidget(self.groupBox_7, 0, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.comboCaminhoInicio = QtGui.QComboBox(self.groupBox_6)
        self.comboCaminhoInicio.setObjectName(_fromUtf8("comboCaminhoInicio"))
        self.horizontalLayout_6.addWidget(self.comboCaminhoInicio)
        self.comboCaminhoFim = QtGui.QComboBox(self.groupBox_6)
        self.comboCaminhoFim.setObjectName(_fromUtf8("comboCaminhoFim"))
        self.horizontalLayout_6.addWidget(self.comboCaminhoFim)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 6, 1, 1, 1)
        self.checkExisteLaco = QtGui.QCheckBox(self.groupBox_6)
        self.checkExisteLaco.setObjectName(_fromUtf8("checkExisteLaco"))
        self.gridLayout_7.addWidget(self.checkExisteLaco, 0, 0, 1, 2)
        self.checkExisteParalela = QtGui.QCheckBox(self.groupBox_6)
        self.checkExisteParalela.setObjectName(_fromUtf8("checkExisteParalela"))
        self.gridLayout_7.addWidget(self.checkExisteParalela, 1, 0, 1, 2)
        self.checkExisteIsolado = QtGui.QCheckBox(self.groupBox_6)
        self.checkExisteIsolado.setObjectName(_fromUtf8("checkExisteIsolado"))
        self.gridLayout_7.addWidget(self.checkExisteIsolado, 2, 0, 1, 2)
        self.checkGrau = QtGui.QCheckBox(self.groupBox_6)
        self.checkGrau.setObjectName(_fromUtf8("checkGrau"))
        self.gridLayout_7.addWidget(self.checkGrau, 7, 0, 1, 2)
        self.checkAdjacencia = QtGui.QCheckBox(self.groupBox_6)
        self.checkAdjacencia.setObjectName(_fromUtf8("checkAdjacencia"))
        self.gridLayout_7.addWidget(self.checkAdjacencia, 8, 0, 1, 2)
        self.checkOrdem = QtGui.QCheckBox(self.groupBox_6)
        self.checkOrdem.setObjectName(_fromUtf8("checkOrdem"))
        self.gridLayout_7.addWidget(self.checkOrdem, 3, 0, 1, 2)
        self.checkExisteCiclo = QtGui.QCheckBox(self.groupBox_6)
        self.checkExisteCiclo.setObjectName(_fromUtf8("checkExisteCiclo"))
        self.gridLayout_7.addWidget(self.checkExisteCiclo, 4, 0, 1, 2)
        self.checkConexo = QtGui.QCheckBox(self.groupBox_6)
        self.checkConexo.setObjectName(_fromUtf8("checkConexo"))
        self.gridLayout_7.addWidget(self.checkConexo, 5, 0, 1, 2)
        self.checkCaminhoCurto = QtGui.QCheckBox(self.groupBox_6)
        self.checkCaminhoCurto.setObjectName(_fromUtf8("checkCaminhoCurto"))
        self.gridLayout_7.addWidget(self.checkCaminhoCurto, 6, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox_6, 0, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.groupBox_5)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.pushGerar = QtGui.QPushButton(self.centralWidget)
        self.pushGerar.setObjectName(_fromUtf8("pushGerar"))
        self.gridLayout.addWidget(self.pushGerar, 2, 0, 1, 1)
        self.layoutWidget = QtGui.QWidget(self.centralWidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 614, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuArquivo = QtGui.QMenu(self.menuBar)
        self.menuArquivo.setObjectName(_fromUtf8("menuArquivo"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.actionSobre = QtGui.QAction(MainWindow)
        self.actionSobre.setObjectName(_fromUtf8("actionSobre"))
        self.menuArquivo.addAction(self.actionSobre)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menuBar.addAction(self.menuArquivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.listVertices, self.lineNomeVertice)
        MainWindow.setTabOrder(self.lineNomeVertice, self.pushAddVertice)
        MainWindow.setTabOrder(self.pushAddVertice, self.pushRemoverVertice)
        MainWindow.setTabOrder(self.pushRemoverVertice, self.listArestas)
        MainWindow.setTabOrder(self.listArestas, self.lineNomeAresta)
        MainWindow.setTabOrder(self.lineNomeAresta, self.pushAddAresta)
        MainWindow.setTabOrder(self.pushAddAresta, self.pushRemoverAresta)
        MainWindow.setTabOrder(self.pushRemoverAresta, self.listConexoes)
        MainWindow.setTabOrder(self.listConexoes, self.comboVertice1)
        MainWindow.setTabOrder(self.comboVertice1, self.comboAresta)
        MainWindow.setTabOrder(self.comboAresta, self.comboVertice2)
        MainWindow.setTabOrder(self.comboVertice2, self.linePesoNo)
        MainWindow.setTabOrder(self.linePesoNo, self.pushAddConexao)
        MainWindow.setTabOrder(self.pushAddConexao, self.checkExisteLaco)
        MainWindow.setTabOrder(self.checkExisteLaco, self.checkExisteParalela)
        MainWindow.setTabOrder(self.checkExisteParalela, self.checkExisteIsolado)
        MainWindow.setTabOrder(self.checkExisteIsolado, self.checkOrdem)
        MainWindow.setTabOrder(self.checkOrdem, self.checkExisteCiclo)
        MainWindow.setTabOrder(self.checkExisteCiclo, self.checkConexo)
        MainWindow.setTabOrder(self.checkConexo, self.checkCaminhoCurto)
        MainWindow.setTabOrder(self.checkCaminhoCurto, self.comboCaminhoInicio)
        MainWindow.setTabOrder(self.comboCaminhoInicio, self.comboCaminhoFim)
        MainWindow.setTabOrder(self.comboCaminhoFim, self.checkGrau)
        MainWindow.setTabOrder(self.checkGrau, self.checkAdjacencia)
        MainWindow.setTabOrder(self.checkAdjacencia, self.pushGerar)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Grafo", None))
        self.groupBox.setTitle(_translate("MainWindow", "Grafo", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Vértices", None))
        self.pushAddVertice.setText(_translate("MainWindow", "A&dicionar", None))
        self.pushRemoverVertice.setText(_translate("MainWindow", "&Remover", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Arestas", None))
        self.pushAddAresta.setText(_translate("MainWindow", "A&dicionar", None))
        self.pushRemoverAresta.setText(_translate("MainWindow", "&Remover", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Conexões", None))
        self.label.setText(_translate("MainWindow", "Peso:", None))
        self.pushAddConexao.setText(_translate("MainWindow", "A&dicionar", None))
        self.pushRemoveConexao.setText(_translate("MainWindow", "Remover", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Opçoes do grafo", None))
        self.checkDirecionado.setText(_translate("MainWindow", "Grafo direcionado", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Identificar", None))
        self.checkExisteLaco.setText(_translate("MainWindow", "Existência de laços", None))
        self.checkExisteParalela.setText(_translate("MainWindow", "Existência de arestas paralelas", None))
        self.checkExisteIsolado.setText(_translate("MainWindow", "Existência de vértice isolado", None))
        self.checkGrau.setText(_translate("MainWindow", "Grau de cada vértice", None))
        self.checkAdjacencia.setText(_translate("MainWindow", "Adjacência dos vértices", None))
        self.checkOrdem.setText(_translate("MainWindow", "Ordem do grafo", None))
        self.checkExisteCiclo.setText(_translate("MainWindow", "Existência de ciclos", None))
        self.checkConexo.setText(_translate("MainWindow", "Se é conexo", None))
        self.checkCaminhoCurto.setText(_translate("MainWindow", "Existe caminho:", None))
        self.pushGerar.setText(_translate("MainWindow", "&Gerar", None))
        self.menuArquivo.setTitle(_translate("MainWindow", "A&rquivo", None))
        self.actionSair.setText(_translate("MainWindow", "Sa&ir", None))
        self.actionSair.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionSobre.setText(_translate("MainWindow", "&Sobre", None))

